### ISSUE TITLE
关于js调用https://payjs.cn/api/jsapi出现跨域问题

### ISSUE THREAD

**Issue by MagicYoung** [yi-ge/payjs#1]
您好，我看了您的demo，在写的时候，用js请求https://payjs.cn/api/jsapi发现跨域的问题，请问该怎么解决？在payjs里已经配置了支付目录

**Comment by MagicYoung** [comment]
ok 我已经找到方法，用代理就可以了

**Comment by yi-ge** [comment]
嗯嗯，恭喜！！
